export const FIXED_VALUATION_DATE = '2025-01-01';

export const defaultQuestionnaire = {
    calculationMethod: 'actual_market',
    projectName: '',
    buildingCadastralNumber: '',
    valuationDate: FIXED_VALUATION_DATE,
    objectType: 'здание',
    actualUse: undefined,
    businessCenterClass: undefined,
    averageRentalRate: null,
    mapPointLat: null,
    mapPointLng: null,
    objectAddress: '',
    addressConfirmed: false,
    district: '',
    nearestMetro: '',
    metroDistance: null,
    cadCost: null,
    permittedUse: '',
    totalArea: null,
    constructionYear: null,
    aboveGroundFloors: null,
    hasBasementFloor: 'no',
    undergroundFloors: null,
    landCadastralNumber: '',
    landArea: null,
    landCadCost: null,
    totalOksAreaOnLand: null,
    referenceFloorCategory: '',
    isHistoricalCenter: null,
    zoneCode: '',
    terZone: '',
    environmentCategory1: '',
    environmentCategory2: '',
    environmentCategory3: '',
    hasPrepayment: undefined,
    hasSecurityDeposit: undefined,
    leasableArea: null,
    occupancyRate: null,
    occupiedArea: null,
    floors: [],
    fieldSourceHints: {},
    nspdBuildingLoaded: false,
    nspdLandLoaded: false,
    marketClassResolved: '',
};
