export const ANALOGUE_COLUMNS = [
    { header: 'id', field: 'id', type: 'string', required: true },
    { header: 'parent_object_type', field: 'parent_object_type', type: 'string' },
    { header: 'model_func', field: 'model_func', type: 'string' },
    { header: 'subgroup', field: 'subgroup', type: 'string' },
    { header: 'func', field: 'func', type: 'string' },
    { header: 'total_area', field: 'total_area', type: 'number' },
    { header: 'class_offer', field: 'class_offer', type: 'string' },
    { header: 'station_name', field: 'station_name', type: 'string' },
    { header: 'address', field: 'address', type: 'string' },
    { header: 'building', field: 'building', type: 'string' },
    { header: 'floor', field: 'floor', type: 'string' },
    { header: 'ground_floors', field: 'ground_floors', type: 'number' },
    { header: 'total_floors', field: 'total_floors', type: 'number' },
    { header: 'underground_floors', field: 'underground_floors', type: 'number' },
    { header: 'price', field: 'price', type: 'number' },
    { header: 'price_per_meter', field: 'price_per_meter', type: 'number' },
    { header: 'nds', field: 'nds', type: 'string' },
    { header: 'nds_description', field: 'nds_description', type: 'string' },
    { header: 'price_per_meter_cut_nds', field: 'price_per_meter_cut_nds', type: 'number' },
    { header: 'description', field: 'description', type: 'string' },
    { header: 'ku', field: 'ku', type: 'string' },
    { header: 'ku_description', field: 'ku_description', type: 'string' },
    { header: 'expl_spends', field: 'expl_spends', type: 'string' },
    { header: 'unit_price', field: 'unit_price', type: 'number' },
    { header: 'cadastral', field: 'cadastral', type: 'string' },
    { header: 'y', field: 'y', type: 'number' },
    { header: 'x', field: 'x', type: 'number' },
    { header: 'lat', field: 'lat', type: 'number' },
    { header: 'lon', field: 'lon', type: 'number' },
    { header: 'district', field: 'district', type: 'string' },
    { header: 'date_offer', field: 'date_offer', type: 'date' },
    { header: 'quarter', field: 'quarter', type: 'string' },
    { header: 'condition_building', field: 'condition_building', type: 'string' },
    { header: 'link', field: 'link', type: 'string' },
    { header: 'screenshot', field: 'screenshot', type: 'string' },
    { header: 'ter_zone', field: 'ter_zone', type: 'string' },
    { header: 'zone_code', field: 'zone_code', type: 'string' },
    { header: 'type_name', field: 'type_name', type: 'string' },
    { header: 'zone_name', field: 'zone_name', type: 'string' },
    { header: 'is_historical_center', field: 'is_historical_center', type: 'string' },
    { header: 'built_year', field: 'built_year', type: 'string' },
    { header: 'expl_year', field: 'expl_year', type: 'string' },
    { header: 'new_life_year', field: 'new_life_year', type: 'string' },
    { header: 'price_offer', field: 'price_offer', type: 'string' },
    { header: 'distance_to_station', field: 'distance_to_station', type: 'string' },
    { header: 'env_category_1', field: 'env_category_1', type: 'string' },
    { header: 'env_category_2', field: 'env_category_2', type: 'string' },
    { header: 'env_business_cnt', field: 'env_business_cnt', type: 'number' },
    { header: 'env_residential_high_cnt', field: 'env_residential_high_cnt', type: 'number' },
    { header: 'env_residential_mid_cnt', field: 'env_residential_mid_cnt', type: 'number' },
    { header: 'env_industrial_cnt', field: 'env_industrial_cnt', type: 'number' },
    { header: 'env_osm_total_cnt', field: 'env_osm_total_cnt', type: 'number' },
    { header: 'env_analyzed_at', field: 'env_analyzed_at', type: 'date' },
];

export const REQUIRED_ANALOGUE_HEADERS = [
    'id',
    'model_func',
    'total_area',
    'address',
    'cadastral',
];