export const MARKET_OFFER_COLUMNS = [
    { header: 'ID', field: 'external_id', type: 'string', required: true },
    { header: 'Тип родительского объекта', field: 'parent_object_type', type: 'string' },
    { header: 'Функционал для модели', field: 'model_functional', type: 'string' },
    { header: 'подгруппа 2025', field: 'subgroup_2025', type: 'string' },
    { header: 'Функция', field: 'function_name', type: 'string' },
    { header: 'Общая площадь по объявлению, кв. м', field: 'area_total', type: 'number' },
    { header: 'Класс  по объявлению', field: 'class_offer', type: 'string' },
    { header: 'Метро', field: 'metro', type: 'string' },
    { header: 'Адрес по объявлению', field: 'address_offer', type: 'string' },
    { header: 'Здание', field: 'building_name', type: 'string' },
    { header: 'Год постройки/ввода в эксплуатацию', field: 'year_built_commissioning', type: 'string' },
    { header: 'Этаж расположения', field: 'floor_location', type: 'string' },
    { header: 'Кол-во наземных этажей', field: 'above_ground_floors', type: 'number' },
    { header: 'Кол-во этажей всего', field: 'total_floors', type: 'number' },
    { header: 'Кол-во подземных этажей', field: 'underground_floors', type: 'number' },
    { header: ' Цена по объявлению (руб./месяц) ', field: 'price_total_month', type: 'number' },
    { header: ' Цена руб./кв.м./месяц ', field: 'price_per_sqm_month', type: 'number' },
    { header: 'НДС', field: 'vat', type: 'string' },
    { header: 'НДС_описание', field: 'vat_description', type: 'string' },
    { header: 'Цена очищенная от НДС, руб./кв.м/мес.', field: 'price_without_vat_per_sqm_month', type: 'number' },
    { header: 'Описание', field: 'description', type: 'string' },
    { header: 'КУ', field: 'utilities_included', type: 'string' },
    { header: 'Коммунальные_услуги_описание', field: 'utilities_description', type: 'string' },
    { header: 'Эксплуатационные_расходы_описание', field: 'opex_description', type: 'string' },
    { header: 'Удельная цена, руб./кв.м. (очищена от КУ и ЭР)', field: 'price_per_sqm_cleaned', type: 'number' },
    { header: 'КН здания', field: 'building_cadastral_number', type: 'string' },
    { header: 'x', field: 'x', type: 'number' },
    { header: 'y', field: 'y', type: 'number' },
    { header: 'Район', field: 'district', type: 'string' },
    { header: 'Дата предложения', field: 'offer_date', type: 'date' },
    { header: 'Квартал', field: 'quarter', type: 'string' },
    { header: 'Состояние помещения', field: 'room_condition', type: 'string' },
    { header: 'Ссылка на объявление', field: 'offer_url', type: 'string' },
    { header: 'Принтскрин', field: 'screenshot', type: 'string' },
];

export const REQUIRED_MARKET_OFFER_HEADERS = [
    'ID',
    'Функционал для модели',
    'Общая площадь по объявлению, кв. м',
    'Адрес по объявлению',
    'КН здания',
];