import test from 'node:test';
import assert from 'node:assert/strict';

import { selectAnalogsByMahalanobis } from '../services/calculationService.js';

test('selectAnalogsByMahalanobis reproduces Lakhta workbook-style shortlist order', () => {
    const questionnaire = {
        valuationDate: '2025-01-01',
        district: 'Приморский',
        metroDistance: 950,
        zoneCode: 'ТП3',
        constructionYear: 2006,
        environmentCategory1: 'промзона',
        environmentCategory2: 'общественно-деловая застройка',
        environmentCategory3: 'многоквартирная жилая застройка',
        isHistoricalCenter: false,
        floors: [
            {
                floorCategory: 'first',
                floorLocation: 'Первый этаж',
                avgLeasableRoomArea: 183,
            },
        ],
    };

    const analogs = [
        {
            id: 'lakhta-153',
            area_total: 153,
            year_built_commissioning: 2017,
            distance_to_metro: 1.27,
            district: 'Фрунзенский',
            zone_code: 'ТП3',
            floor_location: 'первый',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'lakhta-74',
            area_total: 74,
            year_built_commissioning: 2016,
            distance_to_metro: 1.27,
            district: 'Приморский',
            zone_code: 'ТП3',
            floor_location: 'первый',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'lakhta-69',
            area_total: 69.4,
            year_built_commissioning: 2006,
            distance_to_metro: 1.05,
            district: 'Приморский',
            zone_code: 'ТП3',
            floor_location: 'второй',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'lakhta-222',
            area_total: 222,
            year_built_commissioning: 1997,
            distance_to_metro: 0.73,
            district: 'Московский',
            zone_code: 'ТД1-1',
            floor_location: 'цоколь',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'lakhta-295',
            area_total: 295,
            year_built_commissioning: 1975,
            distance_to_metro: 1.4,
            district: 'Московский',
            zone_code: 'ТД3',
            floor_location: 'первый',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'lakhta-180',
            area_total: 180,
            year_built_commissioning: 1997,
            distance_to_metro: 0.73,
            district: 'Московский',
            zone_code: 'ТД1-1',
            floor_location: 'цоколь',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'lakhta-305-a',
            area_total: 305,
            year_built_commissioning: 2003,
            distance_to_metro: 0.96,
            district: 'Выборгский',
            zone_code: 'ТД1-1',
            floor_location: 'первый',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'lakhta-305-b',
            area_total: 305,
            year_built_commissioning: 2003,
            distance_to_metro: 0.96,
            district: 'Выборгский',
            zone_code: 'ТД1-1',
            floor_location: 'первый',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'lakhta-305-c',
            area_total: 305,
            year_built_commissioning: 2003,
            distance_to_metro: 0.96,
            district: 'Выборгский',
            zone_code: 'ТД1-1',
            floor_location: 'первый',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'lakhta-381',
            area_total: 381,
            year_built_commissioning: 1997,
            distance_to_metro: 0.73,
            district: 'Московский',
            zone_code: 'ТД1-1',
            floor_location: 'цоколь',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'lakhta-decoy-1',
            area_total: 950,
            year_built_commissioning: 1988,
            distance_to_metro: 7.1,
            district: 'Колпинский',
            zone_code: 'ТЖ2',
            floor_location: 'подвал',
            environment_category_1: 'промзона',
            environment_historical_center: false,
        },
        {
            id: 'lakhta-decoy-2',
            area_total: 1400,
            year_built_commissioning: 1980,
            distance_to_metro: 12,
            district: 'Центральный',
            zone_code: 'ТЖ1',
            floor_location: 'третий и выше',
            environment_category_1: 'многоквартирная жилая застройка',
            environment_historical_center: true,
        },
    ];

    const { selected } = selectAnalogsByMahalanobis(questionnaire, analogs);

    assert.deepEqual(
        selected.map((item) => item.id).sort(),
        [
            'lakhta-153',
            'lakhta-74',
            'lakhta-69',
            'lakhta-222',
            'lakhta-295',
            'lakhta-180',
            'lakhta-305-a',
            'lakhta-305-b',
            'lakhta-305-c',
            'lakhta-381',
        ].sort()
    );
    assert.equal(selected.length, 10);
});

test('selectAnalogsByMahalanobis reproduces Premier workbook-style shortlist order with environment coding', () => {
    const questionnaire = {
        valuationDate: '2025-01-01',
        district: 'Московский',
        metroDistance: 680,
        zoneCode: 'ТП3',
        constructionYear: 2020,
        environmentCategory1: 'промзона',
        environmentCategory2: 'общественно-деловая застройка',
        environmentCategory3: 'многоквартирная жилая застройка',
        isHistoricalCenter: false,
        floors: [
            {
                floorCategory: 'first',
                floorLocation: 'Первый этаж',
                avgLeasableRoomArea: 685,
            },
        ],
    };

    const analogs = [
        {
            id: 'premier-650',
            area_total: 650,
            year_built_commissioning: 2013,
            distance_to_metro: 1.67267,
            district: 'Московский',
            zone_code: 'ТП3',
            floor_location: 'первый',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'premier-538',
            area_total: 538,
            year_built_commissioning: 2010,
            distance_to_metro: 1.43312,
            district: 'Московский',
            zone_code: 'ТП3',
            floor_location: 'второй',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'premier-708-q3',
            area_total: 708.9,
            year_built_commissioning: 2006,
            distance_to_metro: 1.4235,
            district: 'Московский',
            zone_code: 'ТД1-1',
            floor_location: 'первый',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'premier-708-q4',
            area_total: 708.9,
            year_built_commissioning: 2006,
            distance_to_metro: 1.4235,
            district: 'Московский',
            zone_code: 'ТД1-1',
            floor_location: 'первый',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'premier-844',
            area_total: 844,
            year_built_commissioning: 1997,
            distance_to_metro: 0.7331,
            district: 'Московский',
            zone_code: 'ТД1-1',
            floor_location: 'цоколь',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'premier-500-a',
            area_total: 500,
            year_built_commissioning: 1992,
            distance_to_metro: 3.31373,
            district: 'Московский',
            zone_code: 'ТП3',
            floor_location: 'второй',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'premier-500-b',
            area_total: 500,
            year_built_commissioning: 1992,
            distance_to_metro: 3.31373,
            district: 'Московский',
            zone_code: 'ТП3',
            floor_location: 'второй',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'premier-718',
            area_total: 718.4,
            year_built_commissioning: 2016,
            distance_to_metro: 1.70089,
            district: 'Московский',
            zone_code: 'ТП3',
            floor_location: 'третий и выше',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'premier-700',
            area_total: 700.5,
            year_built_commissioning: 2016,
            distance_to_metro: 1.70089,
            district: 'Московский',
            zone_code: 'ТП3',
            floor_location: 'третий и выше',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'premier-750',
            area_total: 750,
            year_built_commissioning: 2012,
            distance_to_metro: 1.12537,
            district: 'Московский',
            zone_code: 'ТП3',
            floor_location: 'третий и выше',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
        {
            id: 'premier-decoy-env',
            area_total: 680,
            year_built_commissioning: 2020,
            distance_to_metro: 0.7,
            district: 'Московский',
            zone_code: 'ТП3',
            floor_location: 'первый',
            environment_category_1: 'промзона',
            environment_historical_center: false,
        },
        {
            id: 'premier-decoy-history',
            area_total: 685,
            year_built_commissioning: 2020,
            distance_to_metro: 0.68,
            district: 'Московский',
            zone_code: 'ТП3',
            floor_location: 'первый',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: true,
        },
        {
            id: 'premier-decoy-district',
            area_total: 685,
            year_built_commissioning: 2020,
            distance_to_metro: 0.68,
            district: 'Центральный',
            zone_code: 'ТП3',
            floor_location: 'первый',
            environment_category_1: 'промзона',
            environment_category_2: 'общественно-деловая застройка',
            environment_category_3: 'многоквартирная жилая застройка',
            environment_historical_center: false,
        },
    ];

    const { selected } = selectAnalogsByMahalanobis(questionnaire, analogs);

    assert.deepEqual(
        selected.map((item) => item.id).sort(),
        [
            'premier-650',
            'premier-538',
            'premier-708-q3',
            'premier-708-q4',
            'premier-844',
            'premier-500-a',
            'premier-500-b',
            'premier-718',
            'premier-700',
            'premier-750',
        ].sort()
    );
    assert.equal(selected[0]?.id, 'premier-650');
    assert.equal(selected[1]?.id, 'premier-538');
});
